# netlify.toml
[build]
  command = "npm run build"
  publish = ".next"
  base = "/"

[build.environment]
  NODE_VERSION = "20"
  NPM_FLAGS = "--legacy-peer-deps"
  NETLIFY_USE_YARN = "false"
  # Add placeholder values for required environment variables
  NEXT_PUBLIC_SUPABASE_URL = "https://placeholder-supabase-url.supabase.co"
  NEXT_PUBLIC_SUPABASE_ANON_KEY = "placeholder-anon-key"
  NEXT_PUBLIC_GOOGLE_MAPS_API_KEY = "placeholder-google-maps-key"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

[build.processing.html]
  pretty_urls = true

[build.processing.images]
  compress = true

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self' https: data: blob: 'unsafe-inline' 'unsafe-eval'"
